---

# Snakemake options

latency-wait: 60
printshellcmds: True
local-cores: 2
keep-going: True
rerun-incomplete: True
reason: True
restart-times: 0
show-failed-logs: True

# conda option

use-conda: True

# Singularity option

use-singularity: True
singularity-args: "--bind /g/romebioinfo/"


# cluster options
max-jobs-per-second: 1
max-status-checks-per-second: 10
jobs: 400
jobname: "{rule}.{jobid}"
cluster: "sbatch --output=\"jobs/{rule}/slurm_%x_%j.out\" --error=\"jobs/{rule}/slurm_%x_%j.log\" --cpus-per-task={threads} --time={resources.runtime} --mem-per-cpu={resources.mem_cpu_mb} --ntasks=1 --parsable" # --parsable added for handling the timeout exception
cluster-status: "./profile/status-sacct.sh" #  Use to handle timeout exception, do not forget to chmod +x


#useful to increase/decrease nb of threads for a specific rule (threads HAS to be defined in the rule too)
set-threads:
  - download_genome=1
  - download_gtf=1
  - download_gff=1
  - build_bowtie_index=8
  - downloadChromInfo=1
  - download_blacklists=1
  - sort_format_blacklist=1
  - unique_tss=1
  - create_whiteLists=1
  - download_fastq_single=1
  - download_fastq_paired=1


#useful to increase/decrease resources of a specific rule (these resources DO NOT need to be defined in the rule)
# Note that time is not in quote
set-resources:
  - download_genome:runtime=00:45:00
  - download_gtf:runtime=00:30:00
  - download_gff:runtime=00:20:00
  - build_bowtie_index:mem_cpu_mb=1250
  - build_bowtie_index:runtime=02:00:00
  - downloadChromInfo:mem_cpu_mb=2000
  - downloadChromInfo:runtime=00:30:00
  - unique_tss:mem_cpu_mb=2000
  - unique_tss:runtime=00:45:00
  - download_fastq_single:mem_cpu_mb=2000
  - download_fastq_single:runtime=01:00:00
  - download_fastq_paired:mem_cpu_mb=2000
  - download_fastq_paired:runtime=01:00:00


# For some reasons time needs quotes to be read by snakemake
default-resources:
  - mem_cpu_mb=950
  - runtime="00:20:00"
