name: learn-github-actions
on: [push]

env:
  myBoolean: ${{ false }}

jobs:
  check-bats-version-job:
    runs-on: ubuntu-latest
    if: ${{ myBoolean }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: installation
        run: npm install -g bats
      - name: displayVesion
        run: bats -v
  helloscript-job:
    needs: check-bats-version-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run hello script
        run:  bash ./.github/scripts/hello.sh

