name: learn-github-actions
on: 
  push:
    branches-ignore:
      - main

env:
  mascot: Mona
  super_duper_var: totally_awesome

jobs:
  check-bats-version-job:
    runs-on: ubuntu-latest
    if: ${{ 1 == 1}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: installation
        run: npm install -g bats
      - name: displayVesion
        run: bats -v
  helloscript-job:
    needs: check-bats-version-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run hello script
        run:  bash ./.github/scripts/hello.sh
  dump_contexts_to_log:
    needs: helloscript-job
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
  windows_job:
    runs-on: windows-latest
    needs: helloscript-job
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Mona
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Octocat
        env:
          mascot: Octocat
  linux_job:
    runs-on: ubuntu-latest
    needs: helloscript-job
    env:
      mascot: Tux
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Tux
