name: learn-github-actions2
on:
  push:
    paths:
      - 'code/Dockerfile'
# Trigger the workflow when another one has completed
#   workflow_run:
#    workflows: [learn-github-actions]
#    types:
#      - completed

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello"
