name: learn-github-actions
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: installation
        run: npm install -g bats
      - name: displayVesion
        run: bats -v

jobs:
  helloscript-job:
    steps:
      - name: Run hello script
        run: ./.github/scripts/hello.sh
        shell: bash
